---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sbextech/spbbk.sbextech.com/safefile
    - /bin/cp -r ./ $DEPLOYPATH
    - /bin/cp -r ./public/ $DEPLOYPATH/public_html/
    - /bin/php $DEPLOYPATH/artisan optimize